### ISSUE TITLE
Warning: ...

### ISSUE THREAD

**Issue by pitcock** [nikosdion/sortbyfield#1]
@nikosdion thank you for this amazing and useful plugin.

I get a warning message in Joomla 3.9.25 & JoomGallery 3.5.0

Warning: Parameter 2 to plgSystemSortbyfield::onContentPrepareData() expected to be a reference, value given in /www/htdocs/w00ae4e1/CMS_3/libraries/joomla/event/event.php on line 70

**Comment by nikosdion** [comment]
I'm pretty sure that if you trace that back you will see that a third party extension is calling the onContentPrepareData system event in an improper way. Joomla does describe that the second parameter must be a reference, not a value. Some third party developer didn't get the memo.

I can't fix third party code.
