### ISSUE TITLE
Falang »Parameters Translation« support

### ISSUE THREAD

**Issue by reilldesign** [nikosdion/sortbyfield#2]
this very handy extension is unfortunately not supported in the falang componente. it does not appear in the parameters translation tab. it would be great if falang was also supported.

<img width="970" alt="Bildschirmfoto 2022-04-07 um 14 21 01" src="https://user-images.githubusercontent.com/43771555/162197410-a9e8bd91-dff4-458e-a0e7-1c5ce0782bb3.png">

**Comment by nikosdion** [comment]
Sorry, this is not going to happen. Falang overrides the database driver, it does not expose any API for us to use. It's also the wrong way to create multi-language sites.
