### ISSUE TITLE
Q - Could this also be used for modules?

### ISSUE THREAD

**Issue by jjnxpct** [nikosdion/sortbyfield#6]
Hi Nocholas! This looks very interesting for a project I am working on. But I would also need to order articles on a custom date field in a category module. Could this also work for a category module, so we can sort items in the module also on a custom date field? Or does this only apply to menu items that show a blog view?

**Comment by nikosdion** [comment]
No, it would not work as there are no controls for that in a module. We only inject the filtering form controls when editing menu items here:
https://github.com/nikosdion/sortbyfield/blob/76877cb09f332d28e0425fa530f9566f6d519ad4/plugins/system/sortbyfield/src/Extension/SortByField.php#L90-L104
