### ISSUE TITLE
Filtering articles older/newer than current date

### ISSUE THREAD

**Issue by isidrobaq** [nikosdion/sortbyfield#7]
Hi Nic

I'm using your plugin to implement a (very) simple event directory with Joomla articles and custom fields. I needed to get articles filtered so only those with a custom date field value older than today's date would be returned in the query, (using Joomla's archive was not an option, as it modifies articles' URL, and old events need to be listed keeping their old url), so I made a small (and crappy) hack to SortByField.php that did the trick.

Basically, I added/changed this at the end of onComContentArticlesGetListQuery:
```
        $filterValue = (new Date())->format('Y-m-d H:i:s');
	$this->orderByCustomField($query, $fieldId, $sortOrder, $filterValue);
```
and added this after the leftjoin in orderByCustomField
```
      	$query->where(
        $query->qn(sprintf('jcsv%d.value', $fieldId)) . ' > ' . $query->quote($filterValue));
```
Oh, and of course adding use Joomla\CMS\Date\Date; at the top of the file.

I think it would be a great addition to your plugin to get this available as a configuration option in the "Sort by custom field" tab. Maybe one or 2 switches allowing to filter results so that only those older/newer than today's date would be returned. This is specially useful when using Yootheme Pro, as this page builder allows doing a lot of stuff with views but always using the results returned by Joomla's component (so you can't filter them when using pagination).

Thanks a lot for sharing this plugin, it helped me a lot ;).

**Comment by nikosdion** [comment]
This is not ordering, this is filtering. You are _filtering_ articles by the values of their custom fields. This is more like what I'm allowing you to do in https://github.com/nikosdion/plg_system_filtermagic

**Comment by nikosdion** [comment]
To clarify:

* **Ordering** changes which articles appear before other articles. The number of articles displayed in total does not change.
* **Filtering** changes which articles appear at all. The number of articles displayed changes, but not which articles appear before other articles.

Since you are essentially hiding (i.e. filtering out) articles whose custom field value is less than a specific value it's filtering, not ordering: the number of articles displayed does change :)

**Comment by isidrobaq** [comment]
Dammit! How I missed that plugin? You're right, this wouldn't be "sorting" anymore.

In my particular use case, I find it more convenient to get a single plugin doing both things (let's call it "Sort and filter by custom date field" :P). I'll make good use of filtermagic plugin in another project though ;). Thanks!

**Comment by nikosdion** [comment]
You're welcome :)
